// <auto-generated />
namespace MarcinKrupnikLab3Zadanie.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class ClothesMagazine : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ClothesMagazine));
        
        string IMigrationMetadata.Id
        {
            get { return "201912121531103_ClothesMagazine"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
